name: hotels
description: Network and navigation

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  carousel_slider: ^4.2.1
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.15
  import_sorter: ^4.6.0
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
